# Principal Component Analysis

## Wednesday January 20 2016

### Classification

In [1]:
'''

Classification and Regression Trees

'''
from sklearn import tree
import pandas as pd
import numpy as np
from sklearn.cross_validation import train_test_split
from sklearn import metrics
import matplotlib.pyplot as plt

%matplotlib inline


In [2]:
'''
Read, Explore, and Process data
'''

# Read in the data
titanic = pd.read_csv('../../data/titanic.csv')

# Take a  selection of the variables
d = titanic[['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch']]



In [3]:
# Check for missing values in all columns
d.isnull().sum()
d.groupby(['Sex', 'Pclass']).Age.apply(lambda x: x.isnull().sum()) / d.groupby(['Sex', 'Pclass']).Age.count()

# Convert all variables to numeric so for scikit learn
d['Sex'] = np.where(d.Sex == 'female', 1, 0)

# Fill in missing values with the mean value (hint: use .fillna())
d['Age'] = d['Age'].fillna(d['Age'].mean())

# Explore the data to indtify trends in characteristics of survivors
d.Survived.value_counts()                    # How many people lived and died
d.Survived.mean()                            # The survival rate for everyone
d.groupby('Sex').Survived.mean()             # By Sex: women have higher survival rates
d.groupby('Pclass').Survived.mean()          # By Pclass: 1st class passengers have higher survival rates
d.groupby(['Sex', 'Pclass']).Survived.mean() # By Sex and Pclass: Women in the 1st and 2nd classes had the highest survival rates

# Create a proxy variable representing whether the Spouse was on board
d['Spouse'] = ((d.Age > 18) & (d.SibSp >= 1)).astype(int)
d.Spouse.value_counts()
d.groupby(['Pclass', 'Spouse']).Survived.mean() # Having a spouse appears to increase survival in the 1st class only




/Users/ianhansel/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/ianhansel/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/ianhansel/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pyda

Pclass  Spouse
1       0         0.575342
        1         0.742857
2       0         0.473684
        1         0.470588
3       0         0.240786
        1         0.250000
Name: Survived, dtype: float64

In [4]:
'''

Split into training and test datasets, and build the model

'''

survived = d['Survived']
del d['Survived']

d


Pclass  Sex        Age  SibSp  Parch  Spouse
0         3    0  22.000000      1      0       1
1         1    1  38.000000      1      0       1
2         3    1  26.000000      0      0       0
3         1    1  35.000000      1      0       1
4         3    0  35.000000      0      0       0
5         3    0  29.699118      0      0       0
6         1    0  54.000000      0      0       0
7         3    0   2.000000      3      1       0
8         3    1  27.000000      0      2       0
9         2    1  14.000000      1      0       0
10        3    1   4.000000      1      1       0
11        1    1  58.000000      0      0       0
12        3    0  20.000000      0      0       0
13        3    0  39.000000      1      5       1
14        3    1  14.000000      0      0       0
15        2    1  55.000000      0      0       0
16        3    0   2.000000      4      1       0
17        2    0  29.699118      0      0       0
18        3    1  31.000000      1      0       1
19        3    1  29.699118      0      0       0
20        2    0  35.000000      0      0       0
21        2    0  34.000000      0      0       0
22        3    1  15.000000      0      0       0
23        1    0  28.000000      0      0       0
24        3    1   8.000000      3      1       0
25        3    1  38.000000      1      5       1
26        3    0  29.699118      0      0       0
27        1    0  19.000000      3      2       1
28        3    1  29.699118      0      0       0
29        3    0  29.699118      0      0       0
..      ...  ...        ...    ...    ...     ...
861       2    0  21.000000      1      0       1
862       1    1  48.000000      0      0       0
863       3    1  29.699118      8      2       1
864       2    0  24.000000      0      0       0
865       2    1  42.000000      0      0       0
866       2    1  27.000000      1      0       1
867       1    0  31.000000      0      0       0
868       3    0  29.699118      0      0       0
869       3    0   4.000000      1      1       0
870       3    0  26.000000      0      0       0
871       1    1  47.000000      1      1       1
872       1    0  33.000000      0      0       0
873       3    0  47.000000      0      0       0
874       2    1  28.000000      1      0       1
875       3    1  15.000000      0      0       0
876       3    0  20.000000      0      0       0
877       3    0  19.000000      0      0       0
878       3    0  29.699118      0      0       0
879       1    1  56.000000      0      1       0
880       2    1  25.000000      0      1       0
881       3    0  33.000000      0      0       0
882       3    1  22.000000      0      0       0
883       2    0  28.000000      0      0       0
884       3    0  25.000000      0      0       0
885       3    1  39.000000      0      5       0
886       2    0  27.000000      0      0       0
887       1    1  19.000000      0      0       0
888       3    1  29.699118      1      2       1
889       1    0  26.000000      0      0       0
890       3    0  32.000000      0      0       0

[891 rows x 6 columns]

In [22]:
# Now, split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(d,survived, random_state=1)

# Create a decision tree classifier instance (start out with a small tree for interpretability)
ctree = tree.DecisionTreeClassifier(random_state=1, max_depth=2)

# Fit the decision tree classifier
ctree.fit(X_train, y_train)


# Create a feature vector
features = d.columns.tolist()

features


['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Spouse']

In [21]:
X_train

array([[  1.        ,   0.        ,  42.        ,   1.        ,
          0.        ,   1.        ],
       [  3.        ,   0.        ,  29.69911765,   1.        ,
          0.        ,   1.        ],
       [  1.        ,   0.        ,  49.        ,   1.        ,
          0.        ,   1.        ],
       ..., 
       [  2.        ,   0.        ,  21.        ,   0.        ,
          0.        ,   0.        ],
       [  3.        ,   1.        ,  29.69911765,   0.        ,
          0.        ,   0.        ],
       [  3.        ,   0.        ,  21.        ,   0.        ,
          0.        ,   0.        ]])

In [23]:

# How to interpret the diagram?
ctree.classes_


array([0, 1])

In [24]:
# Predict what will happen for 1st class woman
#features
ctree.predict_proba([1, 1, 25, 0, 0, 0])
ctree.predict([1, 1, 25, 0, 0, 0])


array([1])

In [12]:

# Predict what will happen for a 3rd class man
ctree.predict_proba([3, 0, 25, 0, 0, 0])
ctree.predict([3, 0, 25, 0, 0, 0])


array([0])

In [14]:
from StringIO import StringIO
out = StringIO()
out = tree.export_graphviz(ctree, out_file = out)
# OUTPUT DOT LANGUAGE SCRIPTS
print out.getvalue()

digraph Tree {
0 [label="X[1] <= 0.5000\ngini = 0.466075334361\nsamples = 668", shape="box"] ;
1 [label="X[2] <= 13.0000\ngini = 0.294316290131\nsamples = 435", shape="box"] ;
0 -> 1 ;
2 [label="gini = 0.4281\nsamples = 29\nvalue = [  9.  20.]", shape="box"] ;
1 -> 2 ;
3 [label="gini = 0.2449\nsamples = 406\nvalue = [ 348.   58.]", shape="box"] ;
1 -> 3 ;
4 [label="X[0] <= 2.5000\ngini = 0.398460093205\nsamples = 233", shape="box"] ;
0 -> 4 ;
5 [label="gini = 0.1049\nsamples = 126\nvalue = [   7.  119.]", shape="box"] ;
4 -> 5 ;
6 [label="gini = 0.4979\nsamples = 107\nvalue = [ 57.  50.]", shape="box"] ;
4 -> 6 ;
}


In [25]:
from sklearn.tree import export_graphviz
export_graphviz(ctree, out_file='tree_vehicles.dot', feature_names=features)

<open file 'tree_vehicles.dot', mode 'wb' at 0x10be1cb70>

In [27]:
from IPython.display import Image  
dot_data = StringIO()  
tree.export_graphviz(ctree, out_file=dot_data,  
                         feature_names=features,  
                         class_names=survived,  
                         filled=True, rounded=True,  
                         special_characters=True)  
graph = pydot.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

TypeError: export_graphviz() got an unexpected keyword argument 'class_names'

In [26]:

# Which features are the most important?
ctree.feature_importances_

# Clean up the output
pd.DataFrame(zip(features, ctree.feature_importances_)).sort_index(by=1, ascending=False)

# Make predictions on the test set
preds = ctree.predict(X_test)

# Calculate accuracy
metrics.accuracy_score(y_test, preds)

# Confusion matrix
pd.crosstab(y_test, preds, rownames=['actual'], colnames=['predicted'])

# Make predictions on the test set using predict_proba
probs = ctree.predict_proba(X_test)[:,1]

# Calculate the AUC metric
metrics.roc_auc_score(y_test, probs)

# Decision Trees have notorouisly high variance, so what can we do
# to better estimate the out of sample error of a high variance model?



/Users/ianhansel/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:6: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)


0.77874177631578934

In [ ]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
ctree = tree.DecisionTreeClassifier(random_state=1, max_depth=2)

# compare AUC using cross-validation
from sklearn.cross_validation import cross_val_score
cross_val_score(logreg, d, survived, cv=10, scoring='roc_auc').mean()
cross_val_score(ctree, d, survived, cv=10, scoring='roc_auc').mean()


# so far logistic regression is winning..

'''

FINE-TUNING THE TREE

'''
from sklearn.grid_search import GridSearchCV


# check CV score for max depth = 3
ctree = tree.DecisionTreeClassifier(max_depth=3)
np.mean(cross_val_score(ctree, d, survived, cv=5, scoring='roc_auc'))

# check CV score for max depth = 10
ctree = tree.DecisionTreeClassifier(max_depth=10)
np.mean(cross_val_score(ctree, d, survived, cv=5, scoring='roc_auc'))


In [ ]:

# Conduct a grid search for the best tree depth
ctree = tree.DecisionTreeClassifier(random_state=1)
depth_range = range(1, 20)
param_grid = dict(max_depth=depth_range)
grid = GridSearchCV(ctree, param_grid, cv=5, scoring='roc_auc')
grid.fit(d, survived)



In [ ]:

# Check out the scores of the grid search
grid_mean_scores = [result[1] for result in grid.grid_scores_]


# Plot the results of the grid search
plt.figure()
plt.plot(depth_range, grid_mean_scores)
plt.hold(True)
plt.grid(True)
plt.plot(grid.best_params_['max_depth'], grid.best_score_, 'ro', markersize=12, markeredgewidth=1.5,
         markerfacecolor='None', markeredgecolor='r')


In [ ]:

# Get the best estimator
best = grid.best_estimator_

cross_val_score(best, d, survived, cv=10, scoring='roc_auc').mean()
cross_val_score(logreg, d, survived, cv=10, scoring='roc_auc').mean()


# Still not as good as Logistic Regression.. 
# Let's try something else



### EXERCISE ###
''' Use Grid Search try scan over three parameters
1. max_depth:     from 1 to 20
2. criterion:     (either 'gini' or 'entropy')
3. max_features : range (1,5)

'''


### Regression

In [ ]:
# Decision trees (like many other classification models)
# can also be used for regression!


drinks = pd.read_csv('../../data/drinks.csv', na_filter=False)

drinks

# Make dummy columns for each of the 6 regions
for continent_ in ['AS', 'NA', 'EU', 'AF', 'SA', 'OC']:
    drinks[continent_] = drinks['continent'] == continent_

drinks


del drinks['continent']
del drinks['country']
del drinks['total_litres_of_pure_alcohol'] # this doesn't seem fair does it?

X = drinks.drop('wine_servings', axis=1)
y = drinks['wine_servings']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)


rtree = tree.DecisionTreeRegressor()

rtree.fit(X_train, y_train)
rtree.predict(X_test)

scores = cross_val_score(rtree, X, y, cv=10, scoring='mean_squared_error')
mse_scores = -scores
mse_scores
rmse_scores = np.sqrt(mse_scores)
rmse_scores
rmse_scores.mean()

wine_mean = y.mean()
wine_mean

features = X.columns
pd.DataFrame(zip(features, rtree.feature_importances_)).sort_index(by=1, ascending=False)

